# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_listener:
    enabled:              true
    default_format:       json
    decoders:
      json: fos_rest.decoder.json
#  param_fetcher_listener:  true
  body_converter:
    enabled: true
    validate: true
#    allowed_methods_listener:  true
#    routing_loader: true
#  view:
#    view_response_listener:  'force'
#    formats:
#      json: true
  exception:
    enabled: true
  format_listener:
    rules:
      - { priorities: ['json', 'html'], fallback_format: json, prefer_extension: true }
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
